### ISSUE TITLE
Public DSN not working - requires private DSN

### ISSUE THREAD

**Issue by zahiar** [getsentry/sentry_airflow#24]
We've been attempting to make use of this plugin, however we found that a public DSN doesn't quite work for us. We see this appear in the logs but nothing in Sentry itself.

```
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

However, the moment we switch to a private DSN (one where it contains the secret). then it works fine.

I'm using the latest version of this plugin (at time of writing), Airflow version 1.10.3 & Sentry SDK 0.11.2.

Any reason as to why it was originally coded to work with a public DSN only? Is there some config we are missing?

**Comment by AbhiPrasad** [comment]
Hey!

The plugin should allow you to use a public DSN. Do you mind describing how you are running Sentry (on-premise docker, SAAS, etc)?

**Comment by zahiar** [comment]
Sure, it's on-premise, version 8.12.0.

**Comment by AbhiPrasad** [comment]
How are you setting the DSN? Are you using the `SENTRY_DSN` environmental variable, or are you setting a `sentry_dsn` connection in the Airflow webserver UI?

**Comment by zahiar** [comment]
We tried both but public DSN just didn't work for some reason - maybe it could be down to how our Sentry is setup, but either way the private DSN works just fine :)

We did have to make a subtle tweak to the Sentry hook to get the private DSN to work
`dsn = 'https://{conn.login}:{conn.password}@{conn.host}/{conn.schema}'.format(conn=conn)`

Yh we hardcoded the protocol to `HTTPS` as our Sentry is lives behind HTTPS but in Airflow, there is only a `HTTP` connection type, no . `HTTPS` yet...

**Comment by AbhiPrasad** [comment]
Ah yeah `https` is not a valid connection type for the airflow connection: https://github.com/apache/airflow/blob/master/airflow/models/connection.py#L74.

Without more context on your setup, I'm not sure I can debug further, I will be closing the issue seeing that using a private DSN still works fine.

We did merge sentry into airflow master (https://airflow.readthedocs.io/en/latest/errors.html), so if you are willing to run the latest airflow master you can use that. Otherwise, you can wait for the next release of airflow.

The `sentry_airflow` integration is still in active development, so if you have any feature requests or changes feel free to open up another issue. Also, we would love to get more insight into how you are using Airflow (and how Sentry helps), so if you are interested feel free to shoot me an email at aprasad@sentry.io!
